create database retail;
use retail;
select * from retail.brand;
select * from retail.categories;
select * from retail.customers;
select * from retail.order_items;
select * from retail.orders;
select * from retail.products;
select * from retail.staff;
select * from retail.stocks;
select * from retail.stores;

-- Join orders, order_items, and products to display detailed line items.
select o.order_id,o.order_date,oi.quantity,oi.total_price,p.product_id,p.product_name
from retail.orders as o
inner join retail.order_items as oi
on o.order_id=oi.order_id
inner join retail.products as p
on oi.product_id=p.product_id;

-- task 4Write a query to group sales (total_price) by each store_id.
select s.store_name,s.store_id,sum(oi.total_price) as totalsales from retail.orders as o
inner join retail.order_items as oi
on o.order_id=oi.order_id
inner join stores as s
on o.store_id=s.store_id
group by store_id,store_name;

-- task5 Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
select product_name,sum(quantity) as totalquantity,sum(total_price) as totalsales from retail.orderitems
group by product_name 
order by totalquantity desc limit 5;

-- task6 For each customer, return total orders placed, total items purchased, and total revenue.
select c.customer_id,c.first_name,count(o.order_id) as order_count,sum(oi.total_price) as total_revenue from retail.customers as  c
inner join orders as o
on c.customer_id=o.customer_id
inner join orderitems as oi
on o.order_id=oi.order_id
group by customer_id,first_name
order by order_count desc;

-- task 7 Write a query to classify customers into spending brackets (e.g., low, medium, high).--
select customer_id,first_name,total_revenue,
case
when total_revenue > 20000 then"high value"
when total_revenue >=10000 then "medium value"
when total_revenue<10000 then"low value"
end as customersegement
from (select c.customer_id,c.first_name,count(o.order_id) as order_count,sum(oi.total_price) as total_revenue 
from retail.customers as c
inner join orders as o
on c.customer_id=o.customer_id
inner join orderitems as oi
on o.order_id=oi.order_id
group by c.customer_id,c.first_name
order by order_count desc) as revenue;
-- task 8 Analyze total revenue generated by each staff member based on their handled orders.

-- task 9 Write a query to list products where stock quantity < 10 in any store.
